### ISSUE TITLE
Bad styling on registration page

### ISSUE THREAD

**Issue by JesseBoogaard** [JesseBoogaard/KGB#6]
There is no margin on the left side of the content causing it to touch the side of the screen, which shouldn't be the case.

URL could be changed but isn't necessary

Several items are still called signup instead of register.

**Comment by dennisblokland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) issue 6 (styling / benamingen registratie)](https://trello.com/c/FwiUIJkr/93-2-issue-6-styling-benamingen-registratie)

**Comment by JesseBoogaard** [comment]
test
