### ISSUE TITLE
Invite markers not showing occasionally

### ISSUE THREAD

**Issue by JesseBoogaard** [JesseBoogaard/KGB#7]
Invite markers tend to disappear after a certain time, not always, very inconsistent, needs a revision

**Comment by dennisblokland** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Invite markers not showing occasionally #7](https://trello.com/c/gOBqlhBJ/100-2-invite-markers-not-showing-occasionally-7)
